from typing import ForwardRef
import webbrowser
from LexicoVentas import LexicoVentas 
from LexicoInstrucciones import LexicoInstrucciones
class Genera():
    def reporte():
        auxaño = LexicoVentas.lista_mes[0]
        auxmes = LexicoVentas.lista_año[0]
        print("Se ha generado el reporte")
        f = open('202000544-RobertoGomez.html','w')
        f.write("<!doctype html>")
        f.write("<html lang=\"en\">")
        f.write("<head>")
        f.write("<!-- Required meta tags -->")
        f.write(" <meta charset=\"utf-8\">")
        f.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">")
        f.write("<!-- Bootstrap CSS -->")
        f.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We\" crossorigin=\"anonymous\">")
        f.write("<title>Reporte "+ auxmes + "</title>")
        f.write("<style>table, th, td {border: 1px solid black; text-align: center}""</style>")
        f.write("</head>")
        f.write("<body>")
        f.write("<H1 style=\"color:white; background-color:teal\">\n<center> REPORTE VENTAS</center>\n</H1>\n")
        f.write("<h3>"+auxmes+" - "+auxaño+"</h3>")
        total_productos= len(LexicoVentas.lista_total)
        f.write("<h4>Productos ingresados: "+str(total_productos)+"</h4>")
        f.write("<center><table><tr>Tabla Original</tr><tr><th>Posicion</th><th>Producto</th><th>Precio</th><th>Cantidad</th><th>Total</th></tr>")
        a= len(LexicoVentas.original)
        for i in range(a):
            f.write("<tr class=\"table-primary\">")
            f.write("<center><td><h4>"+ str(i+1) +"</h4></td>"+"<td><h4>" +LexicoVentas.original[i].producto +"</h4></td>"+"<td><h4>"+ str(LexicoVentas.original[i].precio)+"</h4></td>"+"<td><h4>"+ str(LexicoVentas.original[i].cantidad)+"</h4></td>"+ "<td><h4>"+str(LexicoVentas.original[i].total)+"</h4></td></center>")
            f.write("</tr>")
        f.write("</table></center>")
        f.write("<center><table><tr>Productos con mas ganancias</tr><tr><th>Posicion</th><th>Producto</th><th>Precio</th><th>Cantidad</th><th>Total</th></tr>")
        b= len(LexicoVentas.lista_original)
        for j in range(b):
            f.write("<tr class=\"table-primary\">")
            f.write("<center><td><h4>"+ str(j+1) +"</h4></td>"+"<td><h4>" +LexicoVentas.lista_original[j].producto +"</h4></td>"+"<td><h4>"+ str(LexicoVentas.lista_original[j].precio)+"</h4></td>"+"<td><h4>"+ str(LexicoVentas.lista_original[j].cantidad)+"</h4></td>"+ "<td><h4>"+str(LexicoVentas.lista_original[j].total)+"</h4></td></center>")
            f.write("</tr>")
        f.write("</table></center>")
        f.write("<center><table><tr>Productos mas Vendido</tr><tr><th>Posicion</th><th>Producto</th><th>Precio</th><th>Cantidad</th><th>Total</th></tr>")
        f.write("<tr class=\"table-primary\">")
        f.write("<center><td><h4>1</h4></td>"+"<td><h4>" +LexicoVentas.lista_mayor[0].producto +"</h4></td>"+"<td><h4>"+ str(LexicoVentas.lista_mayor[0].precio)+"</h4></td>"+"<td><h4>"+ str(LexicoVentas.lista_mayor[0].cantidad)+"</h4></td>"+ "<td><h4>"+str(LexicoVentas.lista_mayor[0].total)+"</h4></td></center>")
        f.write("</tr>")
        f.write("</table></center>")
        f.write("<center><table><tr>Productos menos Vendido</tr><tr><th>Posicion</th><th>Producto</th><th>Precio</th><th>Cantidad</th><th>Total</th></tr>")
        f.write("<tr class=\"table-primary\">")
        f.write("<center><td><h4>1</h4></td>"+"<td><h4>" +LexicoVentas.lista_menor[0].producto +"</h4></td>"+"<td><h4>"+ str(LexicoVentas.lista_menor[0].precio)+"</h4></td>"+"<td><h4>"+ str(LexicoVentas.lista_menor[0].cantidad)+"</h4></td>"+ "<td><h4>"+str(LexicoVentas.lista_menor[0].total)+"</h4></td></center>")
        f.write("</tr>")
        f.write("</table></center>")
        f.write("<!-- Optional JavaScript; choose one of the two! -->")
        f.write("<tr class=\"table-primary\">")
        f.write(" <!-- Option 1: Bootstrap Bundle with Popper -->")
        f.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj\" crossorigin=\"anonymous\"></script>")
        f.write("<!-- Option 2: Separate Popper and Bootstrap JS -->")
        f.write(" <!--")
        f.write("<script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js\" integrity=\"sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp\" crossorigin=\"anonymous\"></script>")
        f.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js\" integrity=\"sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/\" crossorigin=\"anonymous\"></script>")
        f.write("-->")
        f.write("</body>")
        f.write("</html>")
        f.close()